export default {
  "login": "stephenprin",
  "id": 52787881,
  "node_id": "MDQ6VXNlcjUyNzg3ODgx",
  "avatar_url": "https://avatars.githubusercontent.com/u/52787881?v=4",
  "gravatar_id": "",
  "url": "https://api.github.com/users/stephenprin",
  "html_url": "https://github.com/stephenprin",
  "followers_url": "https://api.github.com/users/stephenprin/followers",
  "following_url": "https://api.github.com/users/stephenprin/following{/other_user}",
  "gists_url": "https://api.github.com/users/stephenprin/gists{/gist_id}",
  "starred_url": "https://api.github.com/users/stephenprin/starred{/owner}{/repo}",
  "subscriptions_url": "https://api.github.com/users/stephenprin/subscriptions",
  "organizations_url": "https://api.github.com/users/stephenprin/orgs",
  "repos_url": "https://api.github.com/users/stephenprin/repos",
  "events_url": "https://api.github.com/users/stephenprin/events{/privacy}",
  "received_events_url": "https://api.github.com/users/stephenprin/received_events",
  "type": "User",
  "site_admin": false,
  "name": "Prince Nmezi",
  "company": null,
  "blog": "",
  "location": null,
  "email": null,
  "hireable": null,
  "bio": "Hi, My name is Prince Nmezi, I'm a software developer, having a deep passion for software development and problem-solving and how it can change the tech space",
  "twitter_username": null,
  "public_repos": 53,
  "public_gists": 0,
  "followers": 3,
  "following": 5,
  "created_at": "2019-07-11T12:47:13Z",
  "updated_at": "2022-12-22T13:11:06Z"
};
